### PR TITLE
Fix Docker images

### LINKED ISSUE #2: [Template issue] rust-http
I've been trying to work with the the template for the past few days, and I can't seem to make it work. I've tried different approaches, yet none of the prevailed. I'm trying to use the template for rust-http on Minikube. 

minikube logs:
``` 
Jan 17 18:57:47 minikube kubelet[4528]: E0117 18:57:47.814111    4528 pod_workers.go:191] Error syncing pod 494231c0-7244-46c7-9aa5-18080599afb1 ("newuser-7b9d57f955-99kl2_openfaas-fn(494231c0-7244-46c7-9aa5-18080599afb1)"), skipping: failed to "StartContainer" for "newuser" with CrashLoopBackOff: "back-off 2m40s restarting failed container=newuser pod=newuser-7b9d57f955-99kl2_openfaas-fn(494231c0-7244-46c7-9aa5-18080599afb1)"
Jan 17 18:57:59 minikube kubelet[4528]: E0117 18:57:59.155196    4528 pod_workers.go:191] Error syncing pod 494231c0-7244-46c7-9aa5-18080599afb1 ("newuser-7b9d57f955-99kl2_openfaas-fn(494231c0-7244-46c7-9aa5-18080599afb1)"), skipping: failed to "StartContainer" for "newuser" with CrashLoopBackOff: "back-off 2m40s restarting failed container=newuser pod=newuser-7b9d57f955-99kl2_openfaas-fn(494231c0-7244-46c7-9aa5-18080599afb1)"
Jan 17 18:58:12 minikube kubelet[4528]: E0117 18:58:12.152757    4528 pod_workers.go:191] Error syncing pod 494231c0-7244-46c7-9aa5-18080599afb1 ("newuser-7b9d57f955-99kl2_openfaas-fn(494231c0-7244-46c7-9aa5-18080599afb1)"), skipping: failed to "StartContainer" for "newuser" with CrashLoopBackOff: "back-off 2m40s restarting failed container=newuser pod=newuser-7b9d57f955-99kl2_openfaas-fn(494231c0-7244-46c7-9aa5-18080599afb1)"
Jan 17 18:58:25 minikube kubelet[4528]: E0117 18:58:25.153119    4528 pod_workers.go:191] Error syncing pod 494231c0-7244-46c7-9aa5-18080599afb1 ("newuser-7b9d57f955-99kl2_openfaas-fn(494231c0-7244-46c7-9aa5-18080599afb1)"), skipping: failed to "StartContainer" for "newuser" with CrashLoopBackOff: "back-off 2m40s restarting failed container=newuser pod=newuser-7b9d57f955-99kl2_openfaas-fn(494231c0-7244-46c7-9aa5-18080599afb1)"
Jan 17 18:58:39 minikube kubelet[4528]: E0117 18:58:39.156936    4528 pod_workers.go:191] Error syncing pod 494231c0-7244-46c7-9aa5-18080599afb1 ("newuser-7b9d57f955-99kl2_openfaas-fn(494231c0-7244-46c7-9aa5-18080599afb1)"), skipping: failed to "StartContainer" for "newuser" with CrashLoopBackOff: "back-off 2m40s restarting failed container=newuser pod=newuser-7b9d57f955-99kl2_openfaas-fn(494231c0-7244-46c7-9aa5-18080599afb1)"
```

faas-cli logs:
```
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.
2020-01-17T18:57:45Z Forking - main []
2020-01-17T18:57:45Z 2020/01/17 18:57:45 Started logging stderr from function.
2020-01-17T18:57:45Z 2020/01/17 18:57:45 Started logging stdout from function.
2020-01-17T18:57:45Z 2020/01/17 18:57:45 OperationalMode: http
2020-01-17T18:57:45Z 2020/01/17 18:57:45 Error scanning stdout: read |0: file already closed
2020-01-17T18:57:45Z 2020/01/17 18:57:45 Forked function has terminated: exec: not started
```

the following docker file is just something I've been tried to create the past few hours, but still doesn't work:
```docker
FROM openfaas/of-watchdog:0.7.2 as watchdog

# We are going to build static Rust binary
# Reference: https://github.com/emk/rust-musl-builder
FROM rust:1.35-slim as builder

# Copy of-watchdog binary
COPY --from=watchdog /fwatchdog /usr/bin/fwatchdog
RUN chmod +x /usr/bin/fwatchdog

WORKDIR /home/app

COPY function ./function
COPY main ./main
RUN cd main && cargo build --release
# Build the binary

# Prepare runtime image
FROM debian:stretch-slim

RUN apt-get update -qy \
    && apt-get install -qy ca-certificates

RUN addgroup --system app && adduser --system --group app

RUN mkdir -p /home/app

WORKDIR /home/app

COPY --from=builder /usr/bin/fwatchdog .
COPY --from=builder /home/app/main/target/release/main  .

RUN chown -R app /home/app

USER app

ENV fprocess="./main"
ENV mode="http"
ENV upstream_url="http://127.0.0.1:8080"

HEALTHCHECK --interval=3s CMD [ -e /tmp/.lock ] || exit 1

CMD ["./fwatchdog"]
```
`Back-off restarting failed container kubelet minikube spec.containers{newuser} 6`

### PR DESCRIPTION
**Pull request by piotr-roslaniec**
Closes #2 
@mustiikhalil Please let me know if it solves your issue

### CODE REVIEW

**Comment by alexellis** [comment]
Thank you for looking at this @piotr-roslaniec :pray:

**Review by alexellis — APPROVED** [review]
Approved

**Comment by alexellis** [comment]
This dropped the non-root user and the lightweight base image, please can you revert those parts?

**Comment by mustiikhalil** [comment]
@piotr-roslaniec works like a charm! :D

**Comment by piotr-roslaniec** [comment]
@alexellis I think it's ready for merge

**Review by alexellis — APPROVED** [review]
Looks good. Let's go for it!

**Comment by alexellis** [comment]
Thank you for your PR. I've merged the change now.

**Pull request merged**
